### PR TITLE
Review fix of un-imported Content of Common Cartridge to OLX 

### PR DESCRIPTION
**Pull request by FahadKhalid210**
Fix un-imported contents

Fixes:

- Successfully imported the **learning-application-resource** type when the file suffix is **".html"**.
- Fixed html of images that are not in web_resources 
- Added the static files from the resources directory into the static directory.
- Resolved the errors related to KeyError and AttributeError.

[MichaelRoytman](https://github.com/MichaelRoytman)
[alangsto](https://github.com/alangsto)
[ilee2u](https://github.com/ilee2u)

Kindly review this PR.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @FahadKhalid210!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by openedx-webhooks** [comment]
@FahadKhalid210 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/cc2olx&entry.867055334=https://github.com/openedx/cc2olx/pull/138&entry.1484655318=https://github.com/FahadKhalid210&entry.752974735=2023-05-03+07:21&entry.1917517419=2023-05-03+07:36&entry.2133058324=No) so we can improve your experience in the future.

**Comment by MichaelRoytman** [comment]
@FahadKhalid210 Please review the comment above from `openedx-webooks`. In particular, please sign the contributor agreement. We cannot being reviewing your pull request until you have reviewed the comment and signed the agreement. Thank you.

**Comment by FahadKhalid210** [comment]
@openedx/cla-problems I'm still getting CLA error even after already added in the list. Could you please look into this?

**Comment by e0d** [comment]
@FahadKhalid210 your name is the CLA has been updated.  I see there are some other issues.

First, we use conventional commits, so please amend your commit messages to match our [standard](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).

It also looks like there are some test failures.

**Pull request closed without merging**
